spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    defer-datasource-initialization: true  # ddl-auto 실행 후 스크립트 실행

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

resilience4j:
  circuitbreaker:
    instances:
      postViewCount:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000 # 밀리초 단위 (여기서는 10초)
        permittedNumberOfCallsInHalfOpenState: 5
        minimumNumberOfCalls: 5
        writableStackTraceEnabled: false

auth:
  provider:
    db: true
    ad: false

security:
  jwt:
    cookie:
      path: /
      name: __sid
      domain:
      max-age: 3600
      http-only: true
      secure: false
    secret-key: M39weGRwoaA/SyChBpsw31uv79jgMDOGf6xt3HK8bq8=
    expiration: 86400

crypt:
  aes:
    transformation: AES/CBC/PKCS5Padding
    algorithm: AES
    seedkey: OjK6mHE1ajPt5XUuoTvOvw==
    ivparameter: 8aa1a1a0715811e9
  rsa:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA30kFY16cR8MdVTh2lcFJt6k1SI4WcOo0ZIaKAQf/nQe8kQ7hS7ud53D5wZRMtcHCPtDYcZvKm0lmMeS/0bQUdjTqyhH3XqsaMNxIApP8xH/O+kB9VrNVmqNEXBsBEXcZ1qbTKsk828vvg0lqOo0UwS0NKo/BFJv1kG66AvTi7nvn+/WE31mZ1HShsg58m+6vWHFak4uJ3TA9ruiZvEihzaZbrCTJ1GGop5N6PclatHaj5idmMBKNshYcLkWn7DKpVK6QouwXNX27TSYfakwjTGs9LGkfvxNE4TuWwlcaQVqxT7IHbKk5vbJGpeoc1eqCY9RAd+klKVYaTuSSWejx+wIDAQAB
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDfSQVjXpxHwx1VOHaVwUm3qTVIjhZw6jRkhooBB/+dB7yRDuFLu53ncPnBlEy1wcI+0Nhxm8qbSWYx5L/RtBR2NOrKEfdeqxow3EgCk/zEf876QH1Ws1Wao0RcGwERdxnWptMqyTzby++DSWo6jRTBLQ0qj8EUm/WQbroC9OLue+f79YTfWZnUdKGyDnyb7q9YcVqTi4ndMD2u6Jm8SKHNplusJMnUYaink3o9yVq0dqPmJ2YwEo2yFhwuRafsMqlUrpCi7Bc1fbtNJh9qTCNMaz0saR+/E0ThO5bCVxpBWrFPsgdsqTm9skal6hzV6oJj1EB36SUpVhpO5JJZ6PH7AgMBAAECggEAXWH7t+hssfKfRPH9XnpdK0vANhz+s7Cvws8lznKa7AC9U2mGvha0XoQ4YEZ2oplrdLwBmdoPLUzQSdOiicCnwhw1iddjvpsOtBqcnz9nOoM9fBoWkXklNyxLPb4pfzVxf/17WWyaYE51WFIO9HfmkzgVRpSiqszjMcmtT+k9M4GkswITt4VXUW5e4M1IqSqfCPL/bw66fJy002XUHX0RXpav/QJwrHgnLU5iT1OxiNRB1ObS6AnsP2DkqMU7L6vw1HiOhFjcx0EnkeKaHSM/kCHSdssr06Ix83dBbI15mSqNsiL86Ha1POf5Cpzn99vmqw9Apu/Nl6+9H8UhH1S0CQKBgQDuJM5AW8FBnhk9bZ+0tPL/sL57AxArH6dDJYFdtX+gwkHZvarS0xOVGEWxERt+cGme+PNomG8Tw7MxxyrlNPqMMyD7vkPp5Mtz4Wntk5PoF3bDZuCZ2C4uBtJBrAfcUKgC5tAha4VBxC37Ve0TEM89XGrqXq6VvsJrF3NeyQRu7QKBgQDwBwEY/lASu/WQana0ydb3/1OG6v6Lln342GBMphO+e0aiAgfG6g8xiXFDQqWTvsVidxVWqOtOuxvFw9xvacVPqnuvsMdv0wI4v1EyF+ZuAOiu2rqp6NGXWySI9DXMY0xfSyDNjFHD9FmLpnVoGMaDef7MM3hK6+oBp+5GO3rfhwKBgES8Utu4oBs0asyUK5iY8dpjRVd0FuKbjEeRN7m4fVIFP8R9PiUDz48lJlhpO6pO/+1mpbr25Hir77jaZ8Moe3ij+U0wKaIE68RSt6RfCD3hJ+JWe1VsVEfsqBtUcCBjF1tfC4vZ4OiOm0cEEh2CqI5pcmKbWYDXQn5uklo1YxYxAoGASHzVCAdFh2LcNlDwqIiMMzkYsJYnaWB5ir1N19gP/macXjDeyGPHUt5/JiDqgEQMuD/eYd2BsrUvHfqYh80ZmYWS9OweTtcaxKiCjO5K2M3Nd4D2/nkhUuRjlDisRp12YxD9RxYpW1Rf9py+uEFDMlGVcXXZzkaQ1Q8yFmPAJ+ECgYEAu57eDHXl1MXNPc223xuAQEPx9Hw9w0wVIHq++4LNMr4L9naKvArJ2Fbg1i3ahvuoXU++HyLG+qK5ryctBE6PGf6tkSZuIk8M/2PY9fHCGuWBmaewZzXorRDSOsvruM8WaNPOxodRY7ZEHboqq08HPijjqB7MzXQf0mbHsOiiZjs=