spring:
  datasource:
    url: jdbc:mysql://localhost:3305/security?serverTimezone=UTC&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true  # ddl-auto 실행 후 스크립트 실행

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}