spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true  # ddl-auto 실행 후 스크립트 실행

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

resilience4j:
  circuitbreaker:
    instances:
      postViewCount:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000 # 밀리초 단위 (여기서는 10초)
        permittedNumberOfCallsInHalfOpenState: 5
        minimumNumberOfCalls: 5
        writableStackTraceEnabled: false