
export const getSampleMenus = ( ) => {
    return [
        {
            "id": 46012,
            "frontId": "menu.id.vdi",
            "pageUrl": "/clovirvdi/state/vdi/index",
            "menuName": "자원 관리",
            "menuNameBundleKey": null,
            "parentId": null,
            "sortOrder": 1,
            "depth": 1,
            "menuDescriptionKey": null,
            "tenantId": 1,
            "subMenuList": [
                {
                    "id": 46013,
                    "frontId": "menu.id.vdi.state",
                    "pageUrl": "/clovirvdi/state/vdi/index",
                    "menuName": "VDI 관리",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 1,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.vdi.state",
                    "tenantId": 1,
                    "subMenuList": []
                },
                {
                    "id": 46014,
                    "frontId": "menu.id.vdi.vdideploy",
                    "pageUrl": "/clovirvdi/state/vdideploy/index",
                    "menuName": "VDI 배포",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 2,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.vdi.deploy",
                    "tenantId": 1,
                    "subMenuList": []
                }
            ]
        },
        {
            "id": 46015,
            "frontId": "menu.id.board",
            "pageUrl": "/clovirvdi/board/notice/index",
            "menuName": "게시판 관리",
            "menuNameBundleKey": null,
            "parentId": null,
            "sortOrder": 2,
            "depth": 1,
            "menuDescriptionKey": null,
            "tenantId": 1,
            "subMenuList": [
                {
                    "id": 46016,
                    "frontId": "menu.id.board.notice",
                    "pageUrl": "/clovirvdi/board/notice/index",
                    "menuName": "공지사항 관리",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 1,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.board.notice",
                    "tenantId": 1,
                    "subMenuList": []
                },
                {
                    "id": 46017,
                    "frontId": "menu.id.board.library",
                    "pageUrl": "/clovirvdi/board/library/index",
                    "menuName": "자료실 관리",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 2,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.board.library",
                    "tenantId": 1,
                    "subMenuList": []
                },
                {
                    "id": 46018,
                    "frontId": "menu.id.board.question.answer",
                    "pageUrl": "/clovirvdi/board/qna/index",
                    "menuName": "Q&A 관리",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 3,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.board.question.answer",
                    "tenantId": 1,
                    "subMenuList": []
                },
                {
                    "id": 46019,
                    "frontId": "menu.id.board.faq",
                    "pageUrl": "/clovirvdi/board/faq/index",
                    "menuName": "FAQ 관리",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 4,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.board.faq",
                    "tenantId": 1,
                    "subMenuList": []
                }
            ]
        },
        {
            "id": 46020,
            "frontId": "menu.id.service",
            "pageUrl": "/clovirvdi/service/infra/index",
            "menuName": "서비스 설정",
            "menuNameBundleKey": null,
            "parentId": null,
            "sortOrder": 3,
            "depth": 1,
            "menuDescriptionKey": null,
            "tenantId": 1,
            "subMenuList": [
                {
                    "id": 46021,
                    "frontId": "menu.id.service.infra",
                    "pageUrl": "/clovirvdi/service/infra/index",
                    "menuName": "인프라 서버 관리",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 1,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.service.infra",
                    "tenantId": 1,
                    "subMenuList": []
                },
                {
                    "id": 46022,
                    "frontId": "menu.id.service.approval",
                    "pageUrl": "/clovirvdi/service/approval/index",
                    "menuName": "결재프로세스 관리",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 2,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.service.approval",
                    "tenantId": 1,
                    "subMenuList": []
                },
                {
                    "id": 46023,
                    "frontId": "menu.id.service.vdi.desktop.pool",
                    "pageUrl": "/clovirvdi/service/vdi/desktop/pool/index",
                    "menuName": "데스크탑 풀 관리",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 3,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.service.vdi.desktop.pool",
                    "tenantId": 1,
                    "subMenuList": []
                },
                {
                    "id": 46024,
                    "frontId": "menu.id.service.vdi.deploy.catalog",
                    "pageUrl": "/clovirvdi/service/vdi/deploy/catalog/index",
                    "menuName": "배포 카탈로그 관리",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 4,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.service.vdi.deploy.catalog",
                    "tenantId": 1,
                    "subMenuList": []
                },
                {
                    "id": 46025,
                    "frontId": "menu.id.service.vdi.auto.deploy.policy",
                    "pageUrl": "/clovirvdi/service/vdi/auto/deploy/policy/index",
                    "menuName": "VDI 자동 배포 정책 관리",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 5,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.service.vdi.auto.deploy.policy",
                    "tenantId": 1,
                    "subMenuList": []
                },
                {
                    "id": 46026,
                    "frontId": "menu.id.service.vdi.auto.deploy.request.state",
                    "pageUrl": "/clovirvdi/service/vdi/auto/deploy/request/state/index",
                    "menuName": "VDI 자동 배포 신청 관리",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 6,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.service.vdi.auto.deploy.request.state",
                    "tenantId": 1,
                    "subMenuList": []
                },
                {
                    "id": 46027,
                    "frontId": "menu.id.service.networkpolicy.state",
                    "pageUrl": "/clovirvdi/service/networkpolicy/index",
                    "menuName": "네트워크 정책 관리",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 7,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.service.networkpolicy",
                    "tenantId": 1,
                    "subMenuList": []
                },
                {
                    "id": 46028,
                    "frontId": "menu.id.service.admin.member.state",
                    "pageUrl": "/clovirvdi/service/admin/member/state/index",
                    "menuName": "운영자 관리",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 8,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.service.admin.member.state",
                    "tenantId": 1,
                    "subMenuList": []
                },
                {
                    "id": 46029,
                    "frontId": "menu.id.service.ad.member.state",
                    "pageUrl": "/clovirvdi/service/ad/member/state/index",
                    "menuName": "AD 사용자 관리",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 9,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.service.ad.member.state",
                    "tenantId": 1,
                    "subMenuList": []
                },
                {
                    "id": 46030,
                    "frontId": "menu.id.service.vdi.auto.recall.state",
                    "pageUrl": "/clovirvdi/service/vdi/auto/recall/state/index",
                    "menuName": "VDI 자동 회수 정책 관리",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 10,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.service.vdi.auto.recall.state",
                    "tenantId": 1,
                    "subMenuList": []
                },
                {
                    "id": 46031,
                    "frontId": "menu.id.service.menu",
                    "pageUrl": "/clovirvdi/service/menu/index",
                    "menuName": "메뉴 관리",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 11,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.service.menu",
                    "tenantId": 1,
                    "subMenuList": []
                },
                {
                    "id": 46032,
                    "frontId": "menu.id.service.vcenter",
                    "pageUrl": "/clovirvdi/service/vcenter/index",
                    "menuName": "VCENTER 현황",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 12,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.service.vcenter",
                    "tenantId": 1,
                    "subMenuList": []
                },
                {
                    "id": 46033,
                    "frontId": "menu.id.service.config",
                    "pageUrl": "/clovirvdi/service/environment/config/index",
                    "menuName": "환경 설정",
                    "menuNameBundleKey": null,
                    "parentId": null,
                    "sortOrder": 13,
                    "depth": 2,
                    "menuDescriptionKey": "menu.description.service.menu.environment.config",
                    "tenantId": 1,
                    "subMenuList": []
                }
            ]
        }
    ];
}
